// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV0jeAhJ9O3cVJZz3Q1l2cxUFR8HjO4dA',
    appId: '1:992169880774:web:7012b82b4c756d43f37bc7',
    messagingSenderId: '992169880774',
    projectId: 'mywebsite-ff7d7',
    authDomain: 'mywebsite-ff7d7.firebaseapp.com',
    storageBucket: 'mywebsite-ff7d7.appspot.com',
    measurementId: 'G-5R5JK2G28B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvgY4ZTcYoEGQQm7mZUpCwY-eTWyK-Q-M',
    appId: '1:992169880774:android:f9e5d6b518c11312f37bc7',
    messagingSenderId: '992169880774',
    projectId: 'mywebsite-ff7d7',
    storageBucket: 'mywebsite-ff7d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_Tp6lQrzEWRddssCP-5wecA8dnBptu4',
    appId: '1:992169880774:ios:b621010224ce0b31f37bc7',
    messagingSenderId: '992169880774',
    projectId: 'mywebsite-ff7d7',
    storageBucket: 'mywebsite-ff7d7.appspot.com',
    iosClientId: '992169880774-ktsvhegmmg502fg6mglnrl72fkbd673o.apps.googleusercontent.com',
    iosBundleId: 'com.example.version2',
  );
}
